#!/bin/sh

SUMOLOGIC_HOST="${SUMOLOGIC_HOST:-syslog.collection.us1.sumologic.com}"
SUMOLOGIC_TOKEN="${SUMOLOGIC_TOKEN}"

if [ -z "${SUMOLOGIC_TOKEN}" ]; then
    echo "SUMOLOGIC_TOKEN missing"
    exit 1
fi

KUBERNETES_URL=${KUBERNETES_URL:-https://kubernetes.default.svc}
KUBERNETES_VERIFY_SSL=${KUBERNETES_VERIFY_SSL:-true}
KUBERNETES_PRESERVE_JSON_LOG=${KUBERNETES_PRESERVE_JSON_LOG:-true}

mkdir /etc/fluent

cat << EOF >> /etc/fluent/fluent.conf
# input plugin that exports metrics
<source>
  @type prometheus
</source>

# input plugin that collects metrics from MonitorAgent
<source>
  @type prometheus_monitor
</source>

<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag kubernetes.*
  format json
  read_from_head true
  keep_time_key true
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
  kubernetes_url ${KUBERNETES_URL}
  verify_ssl ${KUBERNETES_VERIFY_SSL}
  preserve_json_log ${KUBERNETES_PRESERVE_JSON_LOG}
</filter>

<filter **>
  @type prometheus

  <metric>
    name fluentd_records_total
    type counter
    desc The total number of records read by fluentd.
  </metric>
</filter>

<match **>
  @type sumologic_cloud_syslog
  host ${SUMOLOGIC_HOST}
  port 6514
  token ${SUMOLOGIC_TOKEN}
</match>
EOF

exec je fluentd
